board/urls.py
from django.urls import path
from board.views import question_views, answer_views

app_name = 'board'
urlpatterns = [
    path('index/',
         question_views.index, name='index'),
    path('', question_views.board_list, name='board_list'),
    path('write/', question_views.board_write, name='board_write'),
    path('detail/<int:pk>/', question_views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', question_views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', question_views.board_modify, name='board_modify'),
    path('<int:pk>/like/', question_views.like, name='like'),
    path('detail/<int:board_id>/answer_create/', answer_views.answer_create, name='answer_create'),

    path('detail/<int:board_id>/vote_question/', answer_views.vote_question, name='vote_question'),
    path('detail/<int:board_id>/vote_answer/', answer_views.vote_answer, name='vote_answer'),

    path('detail/<int:answer_id>/answer_delete/', answer_views.answer_delete, name='answer_delete'),
    path('detail/<int:answer_id>/answer_modify/', answer_views.answer_modify, name='answer_modify'),


    #Free
    path('free_board/', question_views.free_board_list, name='free_board_list'),
    path('free_write/', question_views.free_board_write, name='free_board_write'),
    path('detail/<int:pk>/free/', question_views.free_board_detail, name='free_board_detail'),
    path('detail/<int:pk>/free_delete/', question_views.free_board_delete, name='free_board_delete'),
    path('detail/<int:pk>/free_modify/', question_views.free_board_modify, name='free_board_modify'),
    path('detail/<int:board_id>/free_answer_create/', answer_views.free_answer_create, name='free_answer_create'),

    path('detail/<int:board_id>/free_vote_question/', answer_views.free_vote_question, name='free_vote_question'),
    path('detail/<int:board_id>/free_vote_answer/', answer_views.free_vote_answer, name='free_vote_answer'),

    path('detail/<int:answer_id>/free_answer_delete/', answer_views.free_answer_delete, name='free_answer_delete'),
    path('detail/<int:answer_id>/free_answer_modify/', answer_views.free_answer_modify, name='free_answer_modify'),

    path('search', question_views.search, name='search'),
    ]

hackathon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url='/home/', permanent=True)),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('mateboard/', include('mateboard.urls')),
    path('shareboard/', include('shareboard.urls')),
    path('photo/',include('photo.urls')),
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.hello, name='hello')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mateboard/urls.py
from django.urls import path
from mateboard.views import question_views, answer_views

app_name = 'mateboard'
urlpatterns = [
    path('index/',
         question_views.index, name='index'),
    path('', question_views.board_list, name='board_list'),
    path('write/', question_views.board_write, name='board_write'),
    path('detail/<int:pk>/', question_views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', question_views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', question_views.board_modify, name='board_modify'),
    path('<int:pk>/like/', question_views.like, name='like'),
    path('detail/<int:board_id>/answer_create/', answer_views.answer_create, name='answer_create'),

    path('detail/<int:board_id>/vote_question/', answer_views.vote_question, name='vote_question'),
    path('detail/<int:board_id>/vote_answer/', answer_views.vote_answer, name='vote_answer'),

    path('detail/<int:answer_id>/answer_delete/', answer_views.answer_delete, name='answer_delete'),
    path('detail/<int:answer_id>/answer_modify/', answer_views.answer_modify, name='answer_modify'),



]

shareboard/urls.py
from django.urls import path
from shareboard.views import question_views, answer_views

app_name = 'shareboard'
urlpatterns = [
    path('index/',
         question_views.index, name='index'),
    path('', question_views.board_list, name='board_list'),
    path('write/', question_views.board_write, name='board_write'),
    path('detail/<int:pk>/', question_views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', question_views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', question_views.board_modify, name='board_modify'),
    path('<int:pk>/like/', question_views.like, name='like'),
    path('detail/<int:board_id>/answer_create/', answer_views.answer_create, name='answer_create'),

    path('detail/<int:board_id>/vote_question/', answer_views.vote_question, name='vote_question'),
    path('detail/<int:board_id>/vote_answer/', answer_views.vote_answer, name='vote_answer'),

    path('detail/<int:answer_id>/answer_delete/', answer_views.answer_delete, name='answer_delete'),
    path('detail/<int:answer_id>/answer_modify/', answer_views.answer_modify, name='answer_modify'),


]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from user.models import User

def hello(request):
    context = {}

    login_session = request.session.get('login_session', '')

    if login_session == '':
        context['login_session'] = False
    else:
        context['login_session'] = True

    return render(request, 'home/home.html', context)

home/templates/home/base.html
{% extends 'home/index.html' %}
{% block contents %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PYBO 게시판</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> # JQuery 사용 선언 
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
      <!-- jQuery JS -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
    
    </head>
    {% block script %}
    {% endblock %}
<body>

</body>
</html>
{% endblock %}

home/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>맛남</title>
  <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}"> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a href='/' target='_blank'><img style="position: absolute; top: 10px; left: 100px;" width="150px" height="80px" src='https://ifh.cc/g/v14ylo.png'></a>
      <!-- <a class="navbar-brand" href="#">로고 자리</a> -->
      <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              맛집광장
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'board:board_list' %}">맛집 질문</a></li>
              <li><a class="dropdown-item" href="{% url 'mateboard:board_list' %}">맛집 메이트</a></li>
              <li><a class="dropdown-item" href="{% url 'shareboard:board_list' %}">맛집 공유</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">이벤트</a> -->
            <!-- <li class=welcome><a href="mypage.html">---님 환영합니다.</a> -->

          </li>

          <a href="/" class="btn" style="margin-left: -500px; left: 80px;position: absolute; top: 30px; left: 800px;">홈으로</a>
          <a href="{% url 'board:board_list' %}" class="btn" style="margin-left: -500px; left: 80px;position: absolute; top: 30px; left: 950px;">🥑 맛집 질문 🥑</a>
          <a href="{% url 'shareboard:board_list' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1150px;" >🍧 맛집 공유 🍧</a>
          <a href="{% url 'mateboard:board_list' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1350px;">🌭 맛집 메이트 찾기 🌭</a>

          {% if login_session %}
          <a href="{% url 'user:logout' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1600px;">로그아웃</a>
          {% else %}
          <a href="{% url 'user:login' %}" class="btn"style="margin-left: -500px;position: absolute; top: 35px; left: 1800px;">로그인</a>
          <a href="{% url 'user:register' %}" class="btn" style="margin-left: -500px;position: absolute; top: 35px; left: 1900px;">회원가입</a>
          {% endif %}
          <!-- <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
              </li> -->

        </ul>
      </div>
    </div>
  </nav>



</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>



  <!-- <div style="border: 1px black solid; margin:20px 0px;"></div> -->



  <body class="landing is-preload">
    <div id="page-wrapper">

      <!-- Banner -->
      <section id="banner">
      </section>

      <!-- Main -->

     <img style="display: block;  margin: 0 auto; top: 10px; position: absolute; top: 300px; left: 850px;" width="400px" height="250px" src='https://ifh.cc/g/v14ylo.png'>
     <form style="position: absolute; top: 30px; left: 1700px;" class="form-inline my-2 my-lg-0" action="{% url 'board:search' %}" method="post">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
        <button style="position: absolute; top: 5px; left: 230px;" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
  </body>

  <style type="text/css">
    .navbar {

      background-color: #FF4949 !important;
    }

    .btn {
      color: rgb(255, 255, 255);
      font-weight: bold;
    }

    #footer {
      width: 100%;
      height: 20px;
      bottom: 0px;
    }

    *{
        background-color: #FF4949;
    }
  </style>

</html>

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="kr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>맛남</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">


    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a href='/' target='_blank'><img style="position: absolute; top: 10px; left: 100px;" width="150px" height="80px" src='https://ifh.cc/g/v14ylo.png'></a>
        <!-- <a class="navbar-brand" href="#">로고 자리</a> -->
        <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                맛집광장
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'board:board_list' %}">맛집 질문</a></li>
                <li><a class="dropdown-item" href="{% url 'mateboard:board_list' %}">맛집 메이트</a></li>
                <li><a class="dropdown-item" href="{% url 'shareboard:board_list' %}">맛집 공유</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">이벤트</a> -->
              <!-- <li class=welcome><a href="mypage.html">---님 환영합니다.</a> -->
  
            </li>
  
            <a href="/" class="btn" style="margin-left: -500px; left: 80px;position: absolute; top: 30px; left: 800px;">홈으로</a>
            <a href="{% url 'board:board_list' %}" class="btn" style="margin-left: -500px; left: 80px;position: absolute; top: 30px; left: 950px;">🥑 맛집 질문 🥑</a>
            <a href="{% url 'shareboard:board_list' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1150px;" >🍧 맛집 공유 🍧</a>
            <a href="{% url 'mateboard:board_list' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1350px;">🌭 맛집 메이트 찾기 🌭</a>
  
            {% if login_session %}
            <a href="{% url 'user:logout' %}" class="btn" style="margin-left: -500px;position: absolute; top: 30px; left: 1600px;">로그아웃</a>
            {% else %}
            <a href="{% url 'user:login' %}" class="btn"style="margin-left: -500px;position: absolute; top: 35px; left: 1800px;">로그인</a>
            <a href="{% url 'user:register' %}" class="btn" style="margin-left: -500px;position: absolute; top: 35px; left: 1900px;">회원가입</a>
            {% endif %}
            <!-- <li class="nav-item">
                  <a class="nav-link" href="#">Features</a>
                </li> -->
  
          </ul>
        </div>
      </div>
    </nav>
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>



  <!-- <div style="border: 1px black solid; margin:20px 0px;"></div> -->



  <body class="landing is-preload">
    <div id="page-wrapper">

      <!-- Banner -->
      <section id="banner">
      </section>

      <!-- Main -->
      <section id="main" class="container">
        <p class="pagename">맛남 : 맛집 광장</p>
        <section class="box special">
          {% block contents %}
          <header class="major">
            <h2>요즘 가장 인기있는 맛집은?</h2>
            <div class="box">
              <div class="container-4">
                <input type="search" id="search" placeholder="지역, 식당 또는 음식을 검색해보세요." />
                <button class="icon"><i class="fa fa-search"></i></button>
              </div>
            </div>
          </header>
        </section>

        <div class="row">
          <div class="col-6 col-12-narrower">

            <section class="box special">
              <span class="image featured"><img src="images/pic02.jpg" alt="" /></span>
              <h3>Sed lorem adipiscing</h3>
              <p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum
                phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
              <ul class="actions special">
                <li><a href="#" class="button alt">Learn More</a></li>
              </ul>
            </section>

          </div>
          <div class="col-6 col-12-narrower">

            <section class="box special">
              <span class="image featured"><img src="images/pic03.jpg" alt="" /></span>
              <h3>Accumsan integer</h3>
              <p>Integer volutpat ante et accumsan commophasellus sed aliquam feugiat lorem aliquet ut enim rutrum
                phasellus iaculis accumsan dolore magna aliquam veroeros.</p>
              <ul class="actions special">
                <li><a href="#" class="button alt">Learn More</a></li>
              </ul>
            </section>

          </div>
        </div>

      </section>
      {% endblock contents %}


  </body>

  <style type="text/css">
    .navbar {

      background-color: #FF4949 !important;
    }

    .btn {
      color: rgb(255, 255, 255);
      font-weight: bold;
    }

    #footer {
      width: 100%;
      height: 20px;
      bottom: 0px;
    }
  </style>

</html>

home/templates/home/search.html
{% extends 'base.html' %}

{% block content %}

    {% if not blogs %}

        <h1>검색 결과가 없습니다</h1>

    {% else %}

        {% for board in blogs.all %}
        <div class="container"> 
            <div class="card">
                <div class="card-body">
                    <h1>{{ board.title }}</h1>
                    <p>{{ board.write_dttm | date:"Y-m-d" }}</p>
                    <p>{{ board.contents }}<a href="{% url 'board:board_detail' board.id %}"> ...자세히 보기</a></p> 
                </div>
            </div>
        </div>
        <br>
        {% endfor %}

    {% endif %}

{% endblock %}