board/urls.py
from django.urls import path
from board.views import question_views, answer_views

app_name = 'board'
urlpatterns = [
    path('index/',
         question_views.index, name='index'),
    path('', question_views.board_list, name='board_list'),
    path('write/', question_views.board_write, name='board_write'),
    path('detail/<int:pk>/', question_views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', question_views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', question_views.board_modify, name='board_modify'),
    path('<int:pk>/like/', question_views.like, name='like'),
    path('detail/<int:board_id>/answer_create/', answer_views.answer_create, name='answer_create'),

    path('detail/<int:board_id>/vote_question/', answer_views.vote_question, name='vote_question'),
    path('detail/<int:board_id>/vote_answer/', answer_views.vote_answer, name='vote_answer'),

    path('detail/<int:answer_id>/answer_delete/', answer_views.answer_delete, name='answer_delete'),
    path('detail/<int:answer_id>/answer_modify/', answer_views.answer_modify, name='answer_modify'),


    #Free
    path('free_board/', question_views.free_board_list, name='free_board_list'),
    path('free_write/', question_views.free_board_write, name='free_board_write'),
    path('detail/<int:pk>/free/', question_views.free_board_detail, name='free_board_detail'),
    path('detail/<int:pk>/free_delete/', question_views.free_board_delete, name='free_board_delete'),
    path('detail/<int:pk>/free_modify/', question_views.free_board_modify, name='free_board_modify'),
    path('detail/<int:board_id>/free_answer_create/', answer_views.free_answer_create, name='free_answer_create'),

    path('detail/<int:board_id>/free_vote_question/', answer_views.free_vote_question, name='free_vote_question'),
    path('detail/<int:board_id>/free_vote_answer/', answer_views.free_vote_answer, name='free_vote_answer'),

    path('detail/<int:answer_id>/free_answer_delete/', answer_views.free_answer_delete, name='free_answer_delete'),
    path('detail/<int:answer_id>/free_answer_modify/', answer_views.free_answer_modify, name='free_answer_modify'),

    path('search', question_views.search, name='search'),
    ]

hackathon/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url='/home/', permanent=True)),
    path('user/', include('user.urls')),
    path('board/', include('board.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('mateboard/', include('mateboard.urls')),
    path('shareboard/', include('shareboard.urls')),
    path('photo/',include('photo.urls')),
]

home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.hello, name='hello')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mateboard/urls.py
from django.urls import path
from mateboard.views import question_views, answer_views

app_name = 'mateboard'
urlpatterns = [
    path('index/',
         question_views.index, name='index'),
    path('', question_views.board_list, name='board_list'),
    path('write/', question_views.board_write, name='board_write'),
    path('detail/<int:pk>/', question_views.board_detail, name='board_detail'),
    path('detail/<int:pk>/delete/', question_views.board_delete, name='board_delete'),
    path('detail/<int:pk>/modify/', question_views.board_modify, name='board_modify'),
    path('<int:pk>/like/', question_views.like, name='like'),
    path('detail/<int:board_id>/answer_create/', answer_views.answer_create, name='answer_create'),

    path('detail/<int:board_id>/vote_question/', answer_views.vote_question, name='vote_question'),
    path('detail/<int:board_id>/vote_answer/', answer_views.vote_answer, name='vote_answer'),

    path('detail/<int:answer_id>/answer_delete/', answer_views.answer_delete, name='answer_delete'),
    path('detail/<int:answer_id>/answer_modify/', answer_views.answer_modify, name='answer_modify'),



]

mateboard/models.py
from re import T
from tabnanny import verbose
from tkinter import CASCADE
from django.db import models
from django.urls import reverse


class MateBoard(models.Model):
    title = models.CharField(max_length=64, verbose_name='글 제목')
    contents = models.TextField(verbose_name='글 내용')
    writer = models.ForeignKey('user.User', on_delete=models.CASCADE, verbose_name='작성자')
    write_dttm = models.DateTimeField(auto_now_add=True, verbose_name='글 작성일')

    board_name = models.CharField(max_length=32, default='Python', verbose_name='게시판 종류')
    update_dttm = models.DateTimeField(auto_now_add=True, verbose_name='마지막 수정일')
    hits = models.PositiveBigIntegerField(default=0, verbose_name='조회수')

    like_users = models.ManyToManyField('user.User',
                            related_name='mate_like_articles')
    voter = models.ManyToManyField('user.User', related_name='mate_voter_question')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'mateboard'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'


class MateAnswer(models.Model):
    author = models.ForeignKey('user.User', on_delete=models.CASCADE,
                               related_name='mate_author_answer', null=True, blank=True)
    question = models.ForeignKey(MateBoard, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField(null=True)
    voter = models.ManyToManyField('user.User', related_name='mate_voter_answer')    


    def __str__(self):
        return self.content

mateboard/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from user.models import User

from mateboard.forms import MateAnswerForm
from mateboard.models import MateBoard, MateAnswer



def answer_create(request, board_id):
    login_session = request.session.get('login_session', '')
    context = {'login_session': login_session}

    board = get_object_or_404(MateBoard, id=board_id)

    if request.method == "POST":
        form = MateAnswerForm(request.POST)
        writer = User.objects.get(user_id=login_session)

        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = writer  # 추가한 속성 author 적용
            answer.create_date = timezone.now()
            answer.question = board
            answer.save()
            return redirect(f'/mateboard/detail/{board_id}/')
    else:
        form = MateAnswerForm()
    context = {'question': board, 'form': form}
    return render(request, 'mateboard/board_detail.html', context)


def answer_delete(request, pk):
    login_session = request.session.get('login_session', '')
    board = get_object_or_404(MateBoard, id=pk)

    if board.writer.user_id == login_session:
        board.delete()
        return redirect('/mateboard')
    else:
        return redirect(f'/mateboard/detail/{pk}/')



@login_required
def answer_modify(request, answer_id):
    login_session = request.session.get('login_session', '')
    

    answer = get_object_or_404(MateAnswer, id=answer_id)

    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect(f'/mateboard/detail/{answer_id}/')

    if request.method == 'POST':
        form = MateAnswerForm(request.POST, instance=answer)
        context = {'login_session': login_session,
    'form': form}
        if form.is_valid():
            answer.author = request.user
            answer.modify_at = timezone.now()
            answer.save()
            return redirect('mateboard:answer_modify')
    else:
        form = MateAnswerForm(instance=answer)
        return render(request, 'mateboard/answer_modify.html', context)



def vote_question(request, board_id):
    login_session = request.session.get('login_session', '')

    writer = User.objects.get(user_id=login_session)

    question = get_object_or_404(MateBoard, pk=board_id)
    if request.user == writer:
        messages.error(request, '자신이 작성한 글에는 추천할 수 없습니다.')
    else:
        question.voter.add(writer)
    return redirect(f'/mateboard/detail/{board_id}/', {
        'question_id' : question.id,
        'login_session': login_session
        }
)



def vote_answer(request, board_id):
    login_session = request.session.get('login_session', '')

    author = User.objects.get(user_id=login_session)

    answer = get_object_or_404(MateAnswer, id=board_id)
    if request.user == author:
        messages.error(request, '자신이 작성한 글에는 추천할 수 없습니다.')
    else:
        answer.voter.add(author)
    return redirect('/mateboard',  {
        'question_id':answer.question.id,
        'login_session': login_session
        }
        )

mateboard/views/question_views.py
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import get_object_or_404
from urllib import response
from django.shortcuts import render, redirect, resolve_url
from mateboard.forms import MateBoardWriteForm, MateAnswerForm
from mateboard.models import MateBoard
from user.models import User
from user.decorators import login_required
from datetime import datetime, timedelta
from django.core.paginator import Paginator
from django.db.models import Q, Count
import logging
logger = logging.getLogger('board')

def index(request):
    logger.info("INFO 레벨로 출력")

    # 입력 인자
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':
        question_list = MateBoard.objects.annotate(
            num_voter=Count('voter')).order_by('-num_voter', '-write_dttm')
    elif so == 'popular':
        question_list = MateBoard.objects.annotate(
            num_answer=Count('answer')).order_by('-num_answer', '-write_dttm')
    else:  # recent
        question_list = MateBoard.objects.order_by('-write_dttm')

    # 조회
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 작성자 검색
            Q(answer__author__username__icontains=kw)  # 답변 작성자 검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {
        'question_list': page_obj,
        'page': page, 
        'kw': kw, 
        'so': so,
    }
    return render(request, 'mateboard/board_list.html', context)

def board_list(request):    
    logger.info("INFO 레벨로 출력")
    # 입력 인자
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'recommend':

        question_list = MateBoard.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-write_dttm')

    elif so == 'popular':

        question_list = MateBoard.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-write_dttm')

    else:  # recent

        question_list = MateBoard.objects.order_by('-write_dttm')
    # 조회
    if kw:
        question_list = question_list.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(contents__icontains=kw) |  # 내용 검색
            Q(writer__username__icontains=kw) |  # 질문 작성자 검색
            Q(answer__author__username__icontains=kw)  # 답변 작성자 검색
        ).distinct()

    # 페이징 처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    login_session = request.session.get('login_session', '')
    context = {
        'login_session': login_session,
        'question_list': page_obj,
        'page': page, 
        'kw': kw, 
        'so': so,
    }

    py_boards = MateBoard.objects.filter(
        board_name='Python').order_by('-write_dttm')
    # js_boards = Board.objects.filter(
    #     board_name='JavaScript').order_by('-write_dttm')

    # # page = int(request.GET.get('p', 1))
    # # paginator = Paginator(py_boards, 5)
    # # boards = paginator.get_page(page)

    context['py_boards'] = py_boards
    # context['js_boards'] = js_boards


    return render(request, 'mateboard/board_list.html', context)

    # return render(request, 'board/board_list.html', context)


@login_required
def board_write(request):
    login_session = request.session.get('login_session', '')
    context = {'login_session': login_session}

    if request.method == 'GET':
        write_form = MateBoardWriteForm()
        context['forms'] = write_form
        return render(request, 'mateboard/board_write.html', context)

    elif request.method == 'POST':
        write_form = MateBoardWriteForm(request.POST)

        if write_form.is_valid():
            writer = User.objects.get(user_id=login_session)
            board = MateBoard(
                title=write_form.title,
                contents=write_form.contents,
                writer=writer,
            )
            board.save()


            return redirect('/mateboard')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'mateboard/board_write.html', context)


def board_detail(request, pk):
    login_session = request.session.get('login_session', '')
    context = {'login_session': login_session}

    board = get_object_or_404(MateBoard, id=pk)
    context['board'] = board

    # 글쓴이인지 확인
    if board.writer.user_id == login_session:
        context['writer'] = True
    else:
        context['writer'] = False

    comment_form = MateAnswerForm()

    # response = render(request, 'board/board_detail.html', context)
    response = render(request, 'mateboard/board_detail.html', {
        'board': board,
        'comment_form': comment_form,
        'login_session': login_session,
    }
    )

    # 조회수 기능 (쿠키 이용)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(
        hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()

    cookie_value = request.COOKIES.get('hitboard', '_')

    if f'_{pk}_' not in cookie_value:
        cookie_value += f'{pk}_'
        response.set_cookie('hitboard', value=cookie_value,
                            max_age=max_age, httponly=True)
        board.hits += 1
        board.save()
    return response


def board_delete(request, pk):
    login_session = request.session.get('login_session', '')
    board = get_object_or_404(MateBoard, id=pk)

    if board.writer.user_id == login_session:
        board.delete()
        return redirect('/board')
    else:
        return redirect(f'/board/detail/{pk}/')


@login_required
def board_modify(request, pk):
    login_session = request.session.get('login_session', '')
    context = {'login_session': login_session}

    board = get_object_or_404(MateBoard, id=pk)
    context['board'] = board

    if board.writer.user_id != login_session:
        return redirect(f'/board/detail/{pk}/')

    if request.method == 'GET':
        write_form = MateBoardWriteForm(instance=board)
        context['forms'] = write_form
        return render(request, 'board/board_modify.html', context)

    elif request.method == 'POST':
        write_form = MateBoardWriteForm(request.POST)

        if write_form.is_valid():
            board.title = write_form.title,
            board.contents = write_form.contents,
            board.board_name = write_form.board_name

            board.save()
            return redirect('/board')
        else:
            context['forms'] = write_form
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'board/board_modify.html', context)





def like(request, pk):
    article = get_object_or_404(MateBoard, pk=pk)

    if request.user in article.like_users.all():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
        return redirect('board:board_detail', article.pk)

mateboard/templates/mateboard/answer_modify.html
{% extends 'home/index.html' %}

{% block contents %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "includes/form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

mateboard/templates/mateboard/answer_write.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판 글쓰기</div>
<form action="" method="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {% endfor %}

    {% if error %}
    {{error}}
    {% endif %}
    <button type="submit">저장하기</button>
    <a href="/mateboard" class="btn btn-secondary">돌아가기</a>
    </form>

</form>


{% endblock contents %}

mateboard/templates/mateboard/board_detail.html
{% extends 'home/base.html' %}
{% load static %}
{% load pybo_filter %}
{% block contents %}

<div class="write">📌게시판 상세보기</div>
<br/>
<a href="#" class= "recommend btn btn-sm btn-secondary btn-block my-1" onclick="return confirm('작성자에게 정보가 전달됩니다. 정말 신청하시겠습니까?')">신청하기</a>
<!-- <div style="border: 1px black solid; margin:20px 0px;"></div> -->

<!-- <a href="/board/detail/{{board.id}}/modify/"><button>수정</button></a>
<a href="/board/detail/{{board.id}}/delete/"><button>삭제</button></a> -->



<!-- Main -->



<div class="container mt-3">
    <h2 class="border-bottom py-2">

        <!-- <div>
            게시판 종류 : {{board.board_name}}
        </div> -->
        <div class="write">
            작성자 : {{board.writer}} | 작성일 : {{board.write_dttm}} | 조회수 : {{board.hits}}
        </div>
        <br/>
        <div class="write">
            제목 : {{board.title}}
    </h2>
</div>
<!-- 질문영역 추천영역 -->
<div class="row my-3">
    <div class="col-1">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{board.voter.count}}</div>
        <a href="{% url 'mateboard:vote_question' board.id %}"
            class="recommend btn btn-sm btn-secondary btn-block my-1" onclick="return confirm('이 글을 추천하시겠습니까?')">추천</a>
    </div>
    <!-- 질문영역 추천영역 -->
    <div class="col-11 ">
        <div class="card">
            <div class="card-body">
                <div class="card-text">

                    📍내용📍 : {{board.contents|mark}}</div>
                    {% if board.writer.user_id == login_session %}
                    <a href="/mateboard/detail/{{board.id}}/modify/" class="btn btn-secondary">수정</a>
                    <a href="/mateboard/detail/{{board.id}}/delete/" class="btn btn-secondary "onclick="return confirm('정말 삭제하시겠습니까?')">삭제</a>
                    {% endif %}
            </div>
        </div>



        <!-- #### 답변의 개수를 확인하기 위한 코드 ##### -->
        <h5 class="border-bottom my-3 py-2">📍{{board.mateanswer_set.count}}개의 답변이 있습니다.📍</h5>
        {% for answer in board.mateanswer_set.all %}


        <!-- 답변 추천영역 -->
        <div class="row my-3">
            <div class="col-1">
                <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{answer.voter.count}}</div>
                <a href="{% url 'mateboard:vote_answer' answer.id %}"
                    class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
            </div>
            <!-- 답변 추천영역 -->


            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text" style="white-space: pre-line;">{{ answer.content|mark }}</div>
                        {% if answer.author.user_id == login_session %}
                    <a href="/mateboard/detail/{{answer.id}}/answer_modify/" class="btn btn-secondary">수정</a>
                    <a href="/mateboard/detail/{{answer.id}}/answer_delete/" class="btn btn-secondary">삭제</a>
                    {% endif %}

    
                        <!-- <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }} -->
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

        <form action="{% url 'mateboard:answer_create' board.id %}" method="post" class="my-3">
            {% csrf_token %}
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            {% if answer.author.user_id != board.writer.user_id %}
            <div class="form-group">
                <textarea name="content" id="content" 
                    class="form-control" rows="10"></textarea>
            </div>
            {% endif %}
            <br/>
                <input type="submit" value="답변 등록" class="btn btn-primary">
        </form>
        <!-- <button type="submit" class="btn btn-secondary">답변</button> -->
        <a href="/mateboard" class="btn btn-secondary">돌아가기</a>
        </form>
    </div>

    <style>
        .write{
        font-weight: 700;
        font-size: 28px;
        }
    
    </style>


    {% endblock %}
    {% block script %}
    <script type='text/javascript'>
        $(document).ready(function(){
            $(".delete").on('click', function() {
                if(confirm("정말로 삭제하시겠습니까?")) {
                    location.href = $(this).data('uri');
                }
            });
            $(".recommend").on('click', function() {
                if(confirm("정말로 추천하시겠습니까?")) {
                    location.href = $(this).data('uri');
                }
            });
        });
        </script>
    {% endblock %}

mateboard/templates/mateboard/board_list.html
{% extends 'home/base.html' %}
{% load pybo_filter %}
{% block contents %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>

<div class="board">
    <!-- <div class="py-board"> -->
    <!-- <p>맛집 공유 게시판</p> -->

    <div class="container my-3">
        <div class="row justify-content-between my-3">  <!-- 양쪽정렬 justify-content-between로 변경 -->
            <div class="col-2">
                <select class="form-control so">
                    <option value="recent" {% if so == 'recent' %}selected{% endif %}>
                        최신순
                    </option>
                    <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                        추천순
                    </option>
                    <option value="popular" {% if so == 'popular' %}selected{% endif %}>
                        인기순
                    </option>
                </select>
            </div>
            <div class="col-2 input-group">
                <!-- <input type="text" class="form-control kw" value="{{ kw|default_if_none:"" }}">
                <div class="input-group-append">
                    <button class="btn btn-secondary" type="button" id="btn_search">찾기</button>
                </div> -->
                <div><a href="{% url 'mateboard:board_write' %}" class="btn btn-secondary">새 글쓰기</a></div>

            </div>
            <form id="searchForm" method="get" action="{% url 'board:index' %}">
                <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:"" }}">
                <input type="hidden" id="page" name="page" value="{{ page }}">
                <input type="hidden" id="so" name="so" value="{{ so }}">
            </form>

            <!-- <div style="border: 1px black solid; margin:20px 0px;"></div> -->
        </div>
        <table class="table">
            <thead>
                <tr class="text-center thead-dark">
                <tr>
                    <th>번호</th>
                    <th>추천</th>
                    <th style="width:50%">제목</th>
                    <th>작성자</th>
                    <th>작성일</th>
                </tr>
            </thead>
            <tbody>
                {% if question_list %}
                {% for board in question_list %}
                <tr class="text-center">
                    <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>


                    <td>{{ board.voter.count }}</td>
                    <!-- <td>
                            {% if board.voter.all.count > 0 %}
                            <span class="badge badge-warning px-2 py-1">
                                {{ board.voter.all.count }}
                            </span>
                            {% endif %}
                        </td> -->
                    <td class="text-left">
                        <a href="{% url 'mateboard:board_detail' board.id %}">
                            {{ board.title }}
                            {% if board.mateanswer_set.count > 0 %}
                            <span class="text-danger small ml-2">
                                {{ board.mateanswer_set.count }}
                            </span>
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ board.writer }}</td> <!-- 작성자 추가 -->
                    <td>{{ board.write_dttm }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
                {% endif %}
            </tbody>
        </table>

        <!-- 첫페이지로 돌아가기 -->
        <nav aria-label="pagination" class="mb-4">
            <ul class="pagination justify-content-center">
                {% if question_list.number > 1 %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">처음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">처음</span>
                </li>
                {% endif %}

                <!-- 이전 페이지 구현-->
                {% if question_list.has_other_pages %}
                {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <span class="page-link">이전</span>
                </li>
                {% endif %}

                <!-- 페이징 구현-->
                {% for page_num in question_list.paginator.page_range %}
                {% if question_list.number == page_num %}
                <li class="page-item active">
                    <span class="page-link">{{ page_num }}
                        <span class="sr-only">(current)</span>
                    </span>
                </li>
                {% elif page_num > question_list.number|add:'-4' and page_num < question_list.number|add:'4' %} <li
                    class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}

                    <!-- 다음 페이지 구현-->
                    {% if question_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">다음</span>
                    </li>
                    {% endif %}
                    {% endif %}

                    <!-- 끝으로 돌아가기 -->
                    {% if question_list.number != question_list.paginator.num_pages %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ question_list.paginator.num_pages }}">끝</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">끝</span>
                    </li>
                    {% endif %}
            </ul>
        </nav>

        <form id="searchForm" method="get" action="{% url 'board:board_list' %}">
            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>

    </div>
    <!-- <div>{{board.title}} / {{board.writer}} / {{board.write_dttm}}</div> -->



</div>
<!-- <div class="js-board">
        <p>(자바스크립트 게시판)</p>
        {% for board in js_boards %}
        {% if board %}
        <a href="/board/detail/{{board.id}}" target="_self">
            <div>{{board.title}} / {{board.writer}} / {{board.write_dttm}}</div>
            {% endif %}
            {% endfor %}

    </div> -->




<style>
    .board {
        display: flex;
    }

    .py-board {
        width: 50%;
    }

    .js-board {
        width: 50%;
        border-left: 2px black double;
        padding-left: 25px;
    }

</style>


{% endblock %}
{% block script %}
<script type='text/javascript'>
    $(document).ready(function () {
        $(".page-link").on('click', function () {
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        });

        $("#btn_search").on('click', function () {
            $("#kw").val($(".kw").val());
            $("#page").val(1);  // 검색 버튼을 클릭할 경우 1페이지부터 조회한다.
            $("#searchForm").submit();
        });

        $(".so").on('change', function () {
            $("#so").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
    });
</script>
{% endblock %}

mateboard/templates/mateboard/board_modify.html
{% extends 'home/index.html' %}

{% block contents %}
<div>게시판 수정하기</div>
<form action="" method="POST">
    {% csrf_token %}

    {% for form in forms %}
    <div>
        <label for="{{form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {% endfor %}

    {% if error %}
    {{error}}
    {% endif %}
    <button type="submit">글 수정하기</button>
</form>
{% endblock contents %}